name: Build and Release FreeRDP

on:
  release:
    types: [published]  # 当发布新版本时触发

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install MinGW
      run: |
        choco install mingw --yes

    - name: Install CMake
      run: |
        choco install cmake --yes

    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git C:\vcpkg
        cd C:\vcpkg
        ./bootstrap-vcpkg.bat

    - name: Install Dependencies
      run: |
        C:\vcpkg\vcpkg.exe install zlib
        C:\vcpkg\vcpkg.exe install ffmpeg  # 添加 FFmpeg 安装
        C:\vcpkg\vcpkg.exe integrate install

    - name: Configure with CMake
      run: |
        mkdir build
        cd build
        cmake .. -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake

    - name: Build
      run: |
        cd build
        cmake --build . --config Release

    - name: Upload Release Assets
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.release.tag_name }}  # 使用发布的版本号
        files: build/bin/*  # 调整为你的输出文件路径
        name: FreeRDP ${{ github.event.release.tag_name }}  # 自定义上传文件名
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
